use_default_settings:
  engines:
    keep_only:
      - bing
      - duckduckgo

server:
  secret_key: "replace-with-random-secret"
  bind_address: "0.0.0.0"
  port: 8080
  limiter: false
  public_instance: false

search:
  formats:
    - html
    - json
  safe_search: 0
  default_lang: "zh-CN"

outgoing:
  proxies:
    all://:
      - http://host.docker.internal:7897
  extra_proxy_timeout: 10

engines:
  - name: bing
    disabled: false
  - name: duckduckgo
    disabled: false
